title: "Brendan Hy"
description: [LinkedIn](https://www.linkedin.com/in/brendan-hy-199726195/), email: brendanh189@gmail.com, [resume](brendan-hy-resume-nov22.pdf)
remote_theme: pages-themes/minimal@v0.2.0
